# Initial stuff

In [24]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [26]:
pip install pytorch-fid

  Created wheel for pytorch-fid: filename=pytorch_fid-0.2.0-cp37-none-any.whl size=10547 sha256=000e22d1334f4a0693893c840478a93d9994f93f4fe3e2312a8f92d9fb255bb0
  Stored in directory: /root/.cache/pip/wheels/72/36/3c/4f3fb256f62d24bef52636f66f21667bc21caa637ce92f0e53
Successfully built pytorch-fid


In [ ]:
!git clone https://github.com/RKorzeniowski/BigBiGAN-PyTorch.git

Cloning into 'BigBiGAN-PyTorch'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 57 (delta 18), reused 51 (delta 15), pack-reused 0
Unpacking objects: 100% (57/57), done.


# Continued of Loss modes:

This is a second notebook following the first notebook and contains 2 remaining 
loss modes

## no SX

### Train

--loss_mode: "no_sx"

--train: 1

epoch 9, disc_loss 1.564275860786438, gen_enc_loss 0.7596995830535889

In [ ]:
!python "/content/drive/MyDrive/BigBiGAN-PyTorch-main/train_gan.py" --dataset "MNIST" --data_path "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/" --train 1 --loss_mode "no_sx"

2021-05-13 15:59:05.212468: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
0it [00:00, ?it/s]epoch 0, disc_loss 1.9837738275527954, gen_enc_loss 0.04402796924114227
50it [00:49,  1.03it/s]epoch 0, disc_loss 1.0065821409225464, gen_enc_loss 1.7737467288970947
100it [01:38,  1.01it/s]epoch 0, disc_loss 1.0079492330551147, gen_enc_loss 1.609933853149414
150it [02:28,  1.01it/s]epoch 0, disc_loss 1.1134612560272217, gen_enc_loss 1.4438576698303223
200it [03:17,  1.00it/s]epoch 0, disc_loss 1.3377487659454346, gen_enc_loss 1.401383399963379
234it [03:51,  1.01it/s]
0it [00:00, ?it/s]epoch 1, disc_loss 1.4414640665054321, gen_enc_loss 1.2324106693267822
50it [00:57,  1.10s/it]epoch 1, disc_loss 1.3864318132400513, gen_enc_loss 0.827826976776123
100it [01:53,  1.12s/it]epoch 1, disc_loss 1.306912899017334, gen_enc_loss 1.0106557607650757
150it [02:49,  1.11s/it]epoch 1, disc_loss 1.3184442520141602, gen_enc_loss 0.95674777

### Testing

--train: 0

In [ ]:
!python "/content/drive/MyDrive/BigBiGAN-PyTorch-main/train_gan.py" --dataset "MNIST" --data_path "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/" --train 0 --loss_mode "no_sx"

original images saved
creating generated image directory (save one batch
0it [00:00, ?it/s]
  0% 0/256 [00:00<?, ?it/s]
  0% 1/256 [00:00<00:50,  5.10it/s]
  1% 3/256 [00:00<00:40,  6.23it/s]
  2% 4/256 [00:00<00:35,  7.03it/s]
  2% 5/256 [00:00<00:34,  7.20it/s]
  2% 6/256 [00:00<00:34,  7.16it/s]
  3% 7/256 [00:00<00:36,  6.89it/s]
  3% 8/256 [00:01<00:37,  6.55it/s]
  4% 9/256 [00:01<00:40,  6.03it/s]
  4% 10/256 [00:01<00:44,  5.53it/s]
  4% 11/256 [00:01<00:47,  5.13it/s]
  5% 12/256 [00:01<00:52,  4.68it/s]
  5% 13/256 [00:02<00:56,  4.30it/s]
  5% 14/256 [00:02<01:01,  3.93it/s]
  6% 15/256 [00:02<01:05,  3.70it/s]
  6% 16/256 [00:03<01:08,  3.51it/s]
  7% 17/256 [00:03<01:12,  3.28it/s]
  7% 18/256 [00:03<01:16,  3.12it/s]
  7% 19/256 [00:04<01:35,  2.48it/s]
  8% 20/256 [00:04<01:34,  2.50it/s]
  8% 21/256 [00:05<01:35,  2.47it/s]
  9% 22/256 [00:05<01:36,  2.43it/s]
  9% 23/256 [00:06<01:38,  2.37it/s]
  9% 24/256 [00:06<01:42,  2.26it/s]
 10% 25/256 [00:07<01:45,  2.19it/s]


### Linear Accuracy

knn (n=3) classification score : 0.11

I believe results would be better with more training

In [ ]:
train_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/no_sx/encoded/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/no_sx/encoded/test.csv")

train_y, train_X = train_df.loc[:, "0"], train_df.loc[:, "1":"100"]
test_y, test_X = test_df.loc[:, "0"], test_df.loc[:, "1":"100"]

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(train_X, train_y)
neigh.score(test_X, test_y)

0.11117788461538461

### FID

score = 10.53

occluding SX worsens model drastically!!!

In [ ]:
!python -m pytorch_fid "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/org/" "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/no_sx/gen/" --dims 192 --device "cuda"

Downloading: "https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/pt_inception-2015-12-05-6726825d.pth
100% 91.2M/91.2M [00:00<00:00, 123MB/s] 
100% 6/6 [00:51<00:00,  8.60s/it]
100% 6/6 [00:01<00:00,  3.77it/s]
FID:  10.53694765061347


## No SX and No SZ

in this mode S_x and S_z are both turned off but their combination S_xz is still remained

### Training

--loss_mode: "no_sx_sz"

--train: 1

epoch 9, disc_loss 0.0, gen_enc_loss 40.13097381591797

In [ ]:
!python "/content/drive/MyDrive/BigBiGAN-PyTorch-main/train_gan.py" --dataset "MNIST" --data_path "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/" --train 1 --loss_mode "no_sx_sz" --resume 7

Loading data from checkpoint, resuming from epoch: 7
creating model from checkpoint
2021-05-20 15:23:02.755184: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
0it [00:00, ?it/s]epoch 7, disc_loss 0.0, gen_enc_loss 41.08757019042969
50it [00:46,  1.10it/s]epoch 7, disc_loss 0.0, gen_enc_loss 40.55833435058594
100it [01:32,  1.09it/s]epoch 7, disc_loss 0.0, gen_enc_loss 41.22679901123047
150it [02:18,  1.07it/s]epoch 7, disc_loss 0.0, gen_enc_loss 39.203975677490234
200it [03:05,  1.08it/s]epoch 7, disc_loss 0.0, gen_enc_loss 40.48166275024414
234it [03:36,  1.08it/s]
0it [00:00, ?it/s]epoch 8, disc_loss 0.0, gen_enc_loss 40.6639289855957
50it [00:47,  1.08it/s]epoch 8, disc_loss 0.0, gen_enc_loss 39.579322814941406
100it [01:33,  1.08it/s]epoch 8, disc_loss 0.0, gen_enc_loss 41.251155853271484
150it [02:19,  1.09it/s]epoch 8, disc_loss 0.0, gen_enc_loss 40.55229187011719
200it [03:06,  1.08it/s]epoch 8, disc_loss 0.0

### Testing 

--train: 0

Inception Score is ::::::  1.0014774

In [2]:
!python "/content/drive/MyDrive/BigBiGAN-PyTorch-main/train_gan.py" --dataset "MNIST" --data_path "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/" --train 0 --loss_mode "no_sx_sz"

original images saved
creating generated image directory (save one batch
Downloading: "https://download.pytorch.org/models/inception_v3_google-1a9a5a14.pth" to /root/.cache/torch/hub/checkpoints/inception_v3_google-1a9a5a14.pth
100% 104M/104M [00:08<00:00, 12.4MB/s]
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3458: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)
/content/drive/MyDrive/BigBiGAN-PyTorch-main/src/pipeline/pipeline.py:235: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x).data.cpu().numpy()
___________________________________
Inception Score is ::::::  1.0014774
___________________________________
100% 256/256 [09:18<00:00,  2

### Linear Accuracy

0.18209134615384615

better than all other modes?

In [5]:
train_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/no_sx_sz/encoded/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/no_sx_sz/encoded/test.csv")

train_y, train_X = train_df.loc[:, "0"], train_df.loc[:, "1":"100"]
test_y, test_X = test_df.loc[:, "0"], test_df.loc[:, "1":"100"]

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(train_X, train_y)
neigh.score(test_X, test_y)

0.18209134615384615

### FID

FID:  126.5791716644983

very big!

In [8]:
!python -m pytorch_fid "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/org/" "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/no_sx_sz/gen/" --dims 192 --device "cuda"

Downloading: "https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/pt_inception-2015-12-05-6726825d.pth
100% 91.2M/91.2M [00:01<00:00, 64.9MB/s]
100% 6/6 [00:52<00:00,  8.75s/it]
100% 6/6 [00:01<00:00,  3.96it/s]
FID:  126.5791716644983


# InfoGAN: Continued

this is the testing phase of infogan which we trained in the previous notebook

### Testing

Inception Score is ::::::  1.0814807

In [21]:
!python "/content/drive/MyDrive/BigBiGAN-PyTorch-main/train_gan.py" --dataset "MNIST" --data_path "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/" --train 0 --loss_mode "info_gan"

creating C gen directory for InfoGAN
0it [00:00, ?it/s]Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).
Clipping input data to the valid range for imshow with RGB data (

### FID

FID is 

In [80]:
!python -m pytorch_fid "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/org/" "/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/info_gan/gen/" --dims 192 --device "cuda"

Downloading: "https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth" to /root/.cache/torch/hub/checkpoints/pt_inception-2015-12-05-6726825d.pth
100% 91.2M/91.2M [00:01<00:00, 82.6MB/s]
100% 6/6 [00:54<00:00,  9.15s/it]
100% 6/6 [00:01<00:00,  3.93it/s]
FID:  7.761327930667729


### Linear Accuracy

linear accuracy is 

In [25]:
train_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/info_gan/encoded/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/info_gan/encoded/test.csv")

train_y, train_X = train_df.loc[:, "0"], train_df.loc[:, "1":"100"]
test_y, test_X = test_df.loc[:, "0"], test_df.loc[:, "1":"100"]

neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(train_X, train_y)
neigh.score(test_X, test_y)

0.14733573717948717

### Hungarian Matching

In [43]:
import pandas as pd
import numpy as np

train_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/info_gan/encoded/train.csv")
test_df = pd.read_csv("/content/drive/MyDrive/BigBiGAN-PyTorch-main/data/MNIST/bigbigan/info_gan/encoded/test.csv")

# Jobs are class labels
jobs = train_df.loc[:, "0"].astype(int)
# workers are predicted C in infoGAN
workers = train_df.loc[:, "1":"10"]

# predicted C is in one-hot mode -> cast to integer
workers = workers.apply(lambda x: x.argmax(), axis=1)

df = pd.DataFrame(list(zip(jobs, workers)), columns = ['label', 'predict'])
df

label  predict
0          9        9
1          9        1
2          2        2
3          1        1
4          3        0
...      ...      ...
59899      0        9
59900      0        5
59901      8        9
59902      1        8
59903      6        9

[59904 rows x 2 columns]

In [54]:
# Find how many times each label-predict pair happens 
# We use this to define cost function
# The more 2 values appear together, the less the cost
res = pd.Series(list(zip(df.label, df.predict))).value_counts()
res

(1, 3)    1544
(0, 5)    1521
(2, 5)    1504
(8, 5)    1485
(3, 5)    1396
          ... 
(8, 7)     205
(3, 7)     199
(2, 7)     187
(0, 7)     183
(5, 7)     178
Length: 100, dtype: int64

this is the cost matrix

In [76]:
# Create worker job matrix
worker_job_matrix = np.zeros((10, 10))

for ind, cost in res.iteritems():
  # - cost 
  worker_job_matrix[ind[0], ind[1]] = - cost

print(worker_job_matrix)

[[ -323.  -257.  -507. -1003.  -819. -1521.  -276.  -183.  -266.  -762.]
 [ -462.  -333.  -375. -1544.  -471. -1294.  -369.  -475.  -619.  -796.]
 [ -331.  -330.  -490. -1055.  -824. -1504.  -300.  -187.  -230.  -697.]
 [ -370.  -368.  -508.  -930.  -854. -1396.  -277.  -199.  -287.  -932.]
 [ -353.  -310.  -463.  -953.  -815. -1191.  -336.  -255.  -426.  -728.]
 [ -402.  -375.  -434.  -748.  -750. -1135.  -287.  -178.  -289.  -809.]
 [ -303.  -384.  -447. -1018.  -823. -1345.  -329.  -221.  -326.  -714.]
 [ -436.  -351.  -502. -1090.  -699. -1299.  -391.  -351.  -449.  -686.]
 [ -319.  -327.  -453. -1012.  -825. -1485.  -248.  -205.  -256.  -714.]
 [ -366.  -367.  -467.  -980.  -799. -1261.  -328.  -283.  -341.  -743.]]


this is the hungarian matching: 

each element in the left array is assigned to the corresponding element in right array

In [77]:
from scipy.optimize import linear_sum_assignment

classes, mapping = linear_sum_assignment(worker_job_matrix)
classes, mapping

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([5, 3, 2, 9, 8, 0, 1, 7, 4, 6]))

finding accuracy in test dataset:::

In [79]:
classes = test_df.loc[:, "0"].astype(int)
predictions = test_df.loc[:, "1":"10"]
predictions = predictions.apply(lambda x: x.argmax(), axis=1)
# Mapping to true classes
predictions = predictions.apply(lambda x: np.where(mapping == x)[0][0])

# Finding Accuracy:
df = pd.DataFrame(list(zip(classes, predictions)), columns=['classes', 'prediction'])
print("Score on test dataset is ")
len(df[df.prediction == df.classes]) / len(df)

Score on test dataset is 


0.1162860576923077